Added Quick Heal and Quick Speed hotkeys
BasicallyIAmFox/DungeonMew pull request #4
Opened 2023-12-01 22:26 UTC by pixelizedgaming

Added quick heal and quick speed hotkeys. Shouldn't be too cheaty since it doesn't actually right click the item for you, just changes active hotbar slot.

2023-12-02 06:06 UTC, BasicallyIAmFox requested changes

2023-12-02 06:06 UTC, BasicallyIAmFox commented on src/main/java/dungeonmew/hotkey/QuickHealHotkey.java
> +                                ( item.getName().getString().equals("Healing Wand") )){
It would be better to compare custom model IDs cause that won't try to compare strings.

2023-12-02 06:06 UTC, BasicallyIAmFox commented on src/main/java/dungeonmew/hotkey/QuickHealHotkey.java
> +                        inv.scrollInHotbar((diff) / Math.abs(diff));
Are you sure you want to do _integer division_ here?

2023-12-02 06:06 UTC, BasicallyIAmFox commented on src/main/java/dungeonmew/hotkey/SpeedSwordHotkey.java
> +                                        item.getName().getString().equals("Magical Sword") )) { // check if hotbar has item
Same as earlier

2023-12-02 17:36 UTC, restics commented on src/main/java/dungeonmew/hotkey/QuickHealHotkey.java
> +                                ( item.getName().getString().equals("Healing Wand") )){
Wait, how would I do that? I tried looking around in other mod repositories and searched the discord but I couldn't come up with anything more optimal. Sorry, I'm kind of unfamiliar with fabric API.

2023-12-02 17:38 UTC, BasicallyIAmFox commented on src/main/java/dungeonmew/hotkey/QuickHealHotkey.java
> +                                ( item.getName().getString().equals("Healing Wand") )){
Looks in ItemStackMixin, or use recently added new class called ItemFacts.

2023-12-03 04:31 UTC, BasicallyIAmFox commented
Please, request review from me whenever you think this is ready for one.

2023-12-03 04:44 UTC, BasicallyIAmFox requested changes
So far LGTM! Though, maybe you could check for highest base amount heal and move to it instead of closest to first slot?
Same for Quick Speed.

2023-12-03 04:44 UTC, BasicallyIAmFox commented on gradle.properties
> +mod_version=1.0.2.2
Shouldn't it be `1.0.2.1`? `1.0.2`->`1.0.2.2` doesn't makes much sense to me

2023-12-03 04:44 UTC, BasicallyIAmFox commented on src/main/java/dungeonmew/hotkey/QuickHealHotkey.java
> +                    for(int j = 0; j <  Math.abs(diff); j++) {
Probably good idea to put `Math.abs(diff)` in a variable, so it doesn't has to be re-calculated every time.

2023-12-03 04:44 UTC, BasicallyIAmFox commented on src/main/java/dungeonmew/hotkey/QuickHealHotkey.java
> +                        inv.scrollInHotbar((diff));
Unnecessary parenthesis.

2023-12-03 04:44 UTC, BasicallyIAmFox commented on src/main/java/dungeonmew/hotkey/QuickHealHotkey.java
> +                                inv.scrollInHotbar((diff));
Same as above.

2023-12-03 04:44 UTC, BasicallyIAmFox commented on src/main/java/dungeonmew/hotkey/QuickHealHotkey.java
> +                        if ((item.isOf(Items.BLAZE_ROD) || item.isOf(Items.STICK)) && (ItemFacts.getBaseHealAmount(item) > 0)){
Couldn't you just check for `ItemFacts.getBaseHealAmount(item) > 0`?
`0` is only returned for items that can't heal player upon use.

2023-12-03 04:44 UTC, BasicallyIAmFox commented on src/main/java/dungeonmew/hotkey/SpeedSwordHotkey.java
> +                        if (item.isOf(Items.DIAMOND_SWORD) && (ItemFacts.getBaseAbilitySpeedAmount(ItemFacts.getCustomModelData(item)) > 0)){
Same as above.

2023-12-03 04:44 UTC, BasicallyIAmFox commented on src/main/java/dungeonmew/hotkey/SpeedSwordHotkey.java
> +                            }
Same as earlier.

2023-12-03 04:44 UTC, BasicallyIAmFox commented on src/main/java/dungeonmew/hotkey/SpeedSwordHotkey.java
> +                    }
Same as earlier.

2023-12-03 06:32 UTC, restics commented on gradle.properties
> +mod_version=1.0.2.2
idk i kind of made 2 sets of changes but whatever works

2023-12-03 06:33 UTC, restics commented on src/main/java/dungeonmew/hotkey/QuickHealHotkey.java
> +                    for(int j = 0; j <  Math.abs(diff); j++) {
true

2023-12-03 06:35 UTC, restics commented on src/main/java/dungeonmew/hotkey/QuickHealHotkey.java
> +                        if ((item.isOf(Items.BLAZE_ROD) || item.isOf(Items.STICK)) && (ItemFacts.getBaseHealAmount(item) > 0)){
i figured it might be more optimal since java checks the left condition first and skips the right one if its false which technically saves 1 or 2 operations but if it looks unclean ill remove it

2023-12-03 06:48 UTC, BasicallyIAmFox commented on src/main/java/dungeonmew/hotkey/QuickHealHotkey.java
> +                        if ((item.isOf(Items.BLAZE_ROD) || item.isOf(Items.STICK)) && (ItemFacts.getBaseHealAmount(item) > 0)){
> i figured it might be more optimal since java checks the left condition first and skips the right one if its false which technically saves 1 or 2 operations but if it looks unclean ill remove it

sure, but if more items are added in future then would have to update this code as well, but with what im suggesting to do could just update in ItemFacts

2023-12-13 16:21 UTC, restics commented
heya i think this branch is good to merge, I have something else cooking but i think its time to close this one since its kind of going off track

2023-12-13 16:22 UTC, pixelizedgaming commented
wait a minute

2023-12-13 16:49 UTC, pixelizedgaming commented
there we go

2023-12-13 17:26 UTC, BasicallyIAmFox approved these changes
Aside unnecessary/missing spaces, it LGTM

2023-12-13 17:39 UTC, merged